Setting.save_default(:ctf_name, 'Parasol')
Setting.save_default(:submit_burst_count, 10)
Setting.save_default(:submit_burst_time, 10)
Setting.save_default(:cooling_down, 900)
Setting.save_default(:rules, '**No rules, No world.**')
Setting.save_default(:team_registrable_from, Time.zone.now)
Setting.save_default(:team_registrable_until, Time.zone.now.weeks_since(2))
Setting.save_default(:contest_starts_at, Time.zone.now.next_month)
Setting.save_default(:contest_ends_at, Time.zone.now.next_month.tomorrow)