Setting.save_default(:ctf_name, 'Parasol')
Setting.save_default(:submit_burst_count, 10)
Setting.save_default(:submit_burst_time, 10)
Setting.save_default(:cooling_down, 900)
Setting.save_default(:rules, '**No rules, No world.**')